version: "3.8"
services:
  mongodb:
    image: "mongo"
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
      - node_modules:/usr/src/app/node_modules
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  node_modules: